name: Labeler

on:
  pull_request_target:
    types:
      - opened
      - ready_for_review

jobs:
    pr-labels:
        # Job to assign PR labels to teams
        name: pr-labels
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Assign labels
              uses: actions/labeler@v4
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/labeler.yml
                  sync-labels: true

    pr-e2e-labels:
        # Job to assign e2e PR labels for cypress tags
        name: pr-e2e-labels
        permissions:
            contents: read
            pull-requests: write
        runs-on: ubuntu-latest
        steps:
            - name: Assign e2e labels
              uses: actions/labeler@v4
              with:
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  configuration-path: .github/e2eLabeler.yml
                  sync-labels: true
